# config/routes.yaml

# the "app_blog_index" route name is not important yet
app_blog:
  path: /blog/
  controller: App\Controller\BlogController::index
#    path: /
#    controller: App\Controller\DefaultController::index
app_index:
  path: /default/
  controller: App\Controller\DefaultController::index