<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCkItyDW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCkItyDW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCkItyDW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCkItyDW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCkItyDW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CkItyDW',
    'container.build_id' => 'd7e0af8c',
    'container.build_time' => 1558949010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCkItyDW');
