<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfZXHn1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfZXHn1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUfZXHn1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUfZXHn1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUfZXHn1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UfZXHn1',
    'container.build_id' => '4c652897',
    'container.build_time' => 1568197091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUfZXHn1');
