<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL70Fd4Q\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL70Fd4Q/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL70Fd4Q.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL70Fd4Q\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerL70Fd4Q\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'L70Fd4Q',
    'container.build_id' => '371a0d69',
    'container.build_time' => 1557759572,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL70Fd4Q');
